# Streamlit secrets file - Add your API keys and secrets here 
# This file is only used in local development, not in Streamlit Cloud
# For Streamlit Cloud, add secrets through their web interface

# Groq API key - replace with your actual key
# GROQ_API_KEY = "your-groq-api-key-here"
